/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GuestbookEntry {
  'creator' : Principal,
  'trailName' : [] | [string],
  'name' : [] | [string],
  'favoritePlace' : [] | [Location],
  'comment' : string,
  'timestamp' : Time,
  'currentLocation' : [] | [Location],
}
export interface Location { 'latitude' : number, 'longitude' : number }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addEntry' : ActorMethod<
    [[] | [string], [] | [string], string, [] | [Location], [] | [Location]],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteEntry' : ActorMethod<[Time], undefined>,
  'getAllEntries' : ActorMethod<[], Array<GuestbookEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntriesWithFavoritePlace' : ActorMethod<[], Array<GuestbookEntry>>,
  'getEntriesWithLocation' : ActorMethod<[], Array<GuestbookEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateEntry' : ActorMethod<
    [
      Time,
      [] | [string],
      [] | [string],
      string,
      [] | [Location],
      [] | [Location],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];