/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const GuestbookEntry = IDL.Record({
  'creator' : IDL.Principal,
  'trailName' : IDL.Opt(IDL.Text),
  'name' : IDL.Opt(IDL.Text),
  'favoritePlace' : IDL.Opt(Location),
  'comment' : IDL.Text,
  'timestamp' : Time,
  'currentLocation' : IDL.Opt(Location),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEntry' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(Location),
        IDL.Opt(Location),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEntry' : IDL.Func([Time], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(GuestbookEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntriesWithFavoritePlace' : IDL.Func(
      [],
      [IDL.Vec(GuestbookEntry)],
      ['query'],
    ),
  'getEntriesWithLocation' : IDL.Func([], [IDL.Vec(GuestbookEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateEntry' : IDL.Func(
      [
        Time,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(Location),
        IDL.Opt(Location),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const GuestbookEntry = IDL.Record({
    'creator' : IDL.Principal,
    'trailName' : IDL.Opt(IDL.Text),
    'name' : IDL.Opt(IDL.Text),
    'favoritePlace' : IDL.Opt(Location),
    'comment' : IDL.Text,
    'timestamp' : Time,
    'currentLocation' : IDL.Opt(Location),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEntry' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(Location),
          IDL.Opt(Location),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEntry' : IDL.Func([Time], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(GuestbookEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntriesWithFavoritePlace' : IDL.Func(
        [],
        [IDL.Vec(GuestbookEntry)],
        ['query'],
      ),
    'getEntriesWithLocation' : IDL.Func(
        [],
        [IDL.Vec(GuestbookEntry)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateEntry' : IDL.Func(
        [
          Time,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(Location),
          IDL.Opt(Location),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };